#!/bin/bash
#var=$1
#
#for i in $*
#do
#        if [ $i -gt $var ]
#        the
#                $var=$i
#fi
#done
echo "Enter How many numbers to sort"
read n


echo "Enter NUmber in array"
for (( i=0; i<$n; i++ ))
do
        read NUM[$i]
done

for (( i=0; i<$n; i++ ))
do
        for (( j=$i; j<$n; j++ ))
        do
                if [ ${NUM[$i]} -gt ${NUM[$j]} ];
                then
                        A=${NUM[$i]}
                        NUM[$i]=${NUM[$j]}
                        NUM[$j]=$A
                fi
        done
done
echo -e "\n Sorted numbers"
for (( i=0; i<$n; i++ ))
do
        echo "${NUM[$i]}"
done


echo  "the second largest number is ${NUM[$n-2]}"
