#!/bin/bash
percent=`df -kh . | awk -F " " '{print $(NF-1)}' | tail -1 | sed "s/%/ /g"`
if (( $percent > 40 ));
	then
		echo "Disk space over utilization" #| mail -s "Free disk space" somashekhar15@gmail.com
	else 
		echo "Disk spaceis not over utilized"
fi
